services:
  - type: web
    name: rplace-api
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: FREEDOM_MODE
        value: "true"
      - key: MAX_SOCKET_MSG_PER_SECOND
        value: "200"
